apiVersion: codefresh.io/v1beta1
kind: PromotionFlow
metadata:
  name: full
  annotations:
    description: ""
spec:
  triggerEnvironment: dev
  steps:
    - environment: qa
      dependsOn:
        - dev
      policy:
        action: commit
        preAction: delay
    - environment: staging
      dependsOn:
        - qa
      policy:
        action: commit
        preAction: delay
    - environment: prod
      dependsOn:
        - staging
      policy:
        action: commit
        preAction: delay
